### ISSUE TITLE
Null safe

### ISSUE THREAD

**Issue by erf** [hathibelagal-dev/text-to-path-maker-for-flutter#5]
Any plans to port it to null safe? Or would you take a PR ?

**Comment by erf** [comment]
Oh, i see now there actually is a PR for this, but i also converted to null-safety [here](https://github.com/erf/text-to-path-maker-for-flutter/tree/null-safe)

**Comment by hathibelagal-dev** [comment]
Very late reply, but this is now fixed.

`text_to_path_maker: ^0.6.0`
